export const labels: Record<string, string> = {
  planning: '规划中',
  active: '进行中',
  done: '已完成',
  archived: '已归档',
  draft: '草稿',
  ready: '待测试',
  testing: '测试中',
  blocked: '阻塞',
  deprecated: '已废弃',
  untested: '未测',
  passed: '通过',
  failed: '失败',
  skipped: '跳过',
  open: '新建',
  in_progress: '处理中',
  resolved: '已解决',
  verified: '已验证',
  closed: '已关闭',
  reopened: '重新打开',
  not_ready: '未就绪',
  approved: '已通过',
  rejected: '已驳回',
  reviewing: '评审中',
  signed: '已签核',
  pending: '待签核',
  in_review: '评审中',
  changes_requested: '需修改',
  manual: '手工',
  candidate: '自动化候选',
  automated: '已自动化',
  new: '待分诊',
  triaged: '已分诊',
  needs_info: '需补充',
  duplicate: '重复',
  accepted: '已接收',
  standard: '正式项目',
  demo: '演示项目',
  test: '测试数据',
  private: '仅自己',
  project: '项目共享',
  admin: '管理员',
  owner: '负责人',
  project_owner: '项目负责人',
  tester: '测试',
  developer: '开发',
  viewer: '只读',
  disabled: '已禁用'
};

export function labelOf(value?: string) {
  if (!value) return '-';
  return labels[value] || value;
}
